"""Email model for generated and sent emails."""

from sqlalchemy import Column, String, Text, Integer, ForeignKey, DateTime, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import enum

from app.db.base import BaseModel


class EmailStatus(str, enum.Enum):
    """Email status in the sending pipeline."""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    SENT = "sent"
    DELIVERED = "delivered"
    BOUNCED = "bounced"


class BounceType(str, enum.Enum):
    """Email bounce types."""
    HARD = "hard"
    SOFT = "soft"
    COMPLAINT = "complaint"


class Email(BaseModel):
    """
    Email model - AI-generated emails for leads.

    Emails are generated by the Scheduler agent and require
    human approval before sending.
    """

    __tablename__ = "emails"

    # Foreign keys
    lead_id = Column(
        UUID(as_uuid=True),
        ForeignKey("leads.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )
    campaign_id = Column(
        UUID(as_uuid=True),
        ForeignKey("campaigns.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # Email content
    subject = Column(String(500), nullable=False)
    body = Column(Text, nullable=False)

    # Status and approval
    status = Column(
        SQLEnum(EmailStatus, name="email_status", create_type=False),
        default=EmailStatus.PENDING,
        nullable=False,
        index=True
    )
    approved_by = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True
    )
    approved_at = Column(DateTime)

    # Sending timestamps
    sent_at = Column(DateTime)
    delivered_at = Column(DateTime)

    # Engagement tracking
    opened_at = Column(DateTime)
    open_count = Column(Integer, default=0, nullable=False)
    clicked_at = Column(DateTime)
    click_count = Column(Integer, default=0, nullable=False)
    replied_at = Column(DateTime)

    # Bounce handling
    bounced_at = Column(DateTime)
    bounce_type = Column(
        SQLEnum(BounceType, name="bounce_type", create_type=False),
        nullable=True
    )

    # Relationships
    lead = relationship("Lead", back_populates="emails")
    campaign = relationship("Campaign", back_populates="emails")
    approved_by_user = relationship("User", back_populates="approved_emails", foreign_keys=[approved_by])

    @property
    def is_opened(self) -> bool:
        """Check if email was opened."""
        return self.opened_at is not None

    @property
    def is_clicked(self) -> bool:
        """Check if email link was clicked."""
        return self.clicked_at is not None

    def __repr__(self) -> str:
        return f"<Email {self.subject[:30]}... ({self.status.value})>"
